src/main/java/com/juniorok/juniorok/config/ApiConfig.java, src/main/resources/application.properties, src/main/resources/static/js/detailmap.js, src/main/resources/templates/detailmap.html
1.회사이름으로 검색하면 지도 조회가능.(추후 다른 검색이 필요할 경우 수정예정)
=> feat : 근무지 위치 조회용 지도 추가

src/main/resources/static/css/sidebar/sidebar.css, src/main/resources/templates/mainboard.html, src/main/resources/templates/sidebar.html, src/main/resources/templates/sidebar_script.html
메인 화면에 컴포넌트를 삽입하는 예제입니다. 하는 김에 메인 화면 배치도 캐러셀이 위로 올라오도록 수정했습니다.
사이드바 css 에서 사용안하는거는 주석처리 해놨습니다. 세부적인 조정은 현지님이 해주세요.
=> 컴포넌트 삽입 예제

src/main/resources/templates/component_template.html
컴포넌트 작업 편의를 위해 기본 템플릿 입니다. 
본인 작업에 맞춰서 component_name 변경하고, `th:block` 내부에 필요한 작업을 수행하시면 됩니다.
```html
<th:block th:fragment="component_name">
<h1>컴포넌트 작업</h1>
</th:block>
```
예를들어 메인에서 아래와 같이 추가합니다.
```html
<aside class="col-2">
<th:block th:insert="~{sidebar :: sidebar}"></th:block>
<th:block th:insert="~{component_template :: component_name}"></th:block>
</aside>
```
`th:block` 내부에 있는 엘리먼트만 추가된 것을 확인할 수 있습니다.
wiki에 사용법 추가로 정리해 둘게요.
=> 컴포넌트 작업용 기본 템플릿 추가

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/UserController.java, src/main/java/com/juniorok/juniorok/domain/User.java, src/main/java/com/juniorok/juniorok/dto/AuthUser.java, src/main/java/com/juniorok/juniorok/repository/UserRepository.java, src/main/java/com/juniorok/juniorok/service/UserAuthService.java, src/main/resources/mapper/user-mapper.xml, src/main/resources/templates/header.html
1. 로그아웃 기능
2. 첫 로그인 시 사용자 정보 데이터베이스에 저장
3. Spring Security 기본 로그인 로그아웃 경로 해제 및 신규 경로 지정
4. 로그인 유지 기능 사용시 사용자 정보를 데이터베이스와 대조하여 권한 부여
=> 사용자 관련 기능 추가 구현

src/main/resources/static/css/board.css, src/main/resources/static/css/carousel.css, src/main/resources/static/css/searchbar.css, src/main/resources/static/js/board.js, src/main/resources/templates/board.html, src/main/resources/templates/carousel.html, src/main/resources/templates/mainboard.html, src/main/resources/templates/searchbar.html
=> feet: 메인 프론트 작업

src/main/resources/templates/header.html, src/main/resources/templates/posts/post_benefits.html, src/main/resources/templates/posts/post_detail.html, src/main/resources/templates/posts/post_header.html, src/main/resources/templates/posts/post_info_etc.html, src/main/resources/templates/posts/post_modal.html, src/main/resources/templates/posts/post_summary.html
closes-gh-32
공고 상세 정보 컴포넌트를 추가하였습니다.
일부 더미데이터를 넣었습니다. 
상단 헤더도 일부 수정하였습니다.
- 로고 크기 증가, 사용자 메뉴 버튼화
=> 공고 상세 정보 컴포넌트

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/AdminController.java, src/main/java/com/juniorok/juniorok/repository/PostRepository.java, src/main/java/com/juniorok/juniorok/service/PostService.java, src/main/resources/mapper/post-mapper.xml, src/main/resources/templates/admin_post.html, src/main/resources/templates/admin_post_table.html, src/main/resources/templates/admin_post_table_script.html
1.관리자 공고 조회
2.관리자 공고 삭제
**나머지 기능 추가 구현예정.
/adminpost 이 페이지만 활성화 되어있습니다.
공고조회가 /adminpost로 연결됩니다.
삭제 기능만 구현되어있습니다. 
(추후 수정, 내용보기(링크)) 걸 예정입니다.
=> feat : 관리자 화면 공고 조회/삭제

build.gradle, src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/java/com/juniorok/juniorok/domain/Company.java, src/main/java/com/juniorok/juniorok/form/PostForm.java, src/main/java/com/juniorok/juniorok/repository/CompanyRepository.java, src/main/java/com/juniorok/juniorok/repository/PostRepository.java, src/main/java/com/juniorok/juniorok/service/CompanyService.java, src/main/java/com/juniorok/juniorok/service/PostService.java, src/main/resources/mapper/company-mapper.xml, src/main/resources/mapper/post-mapper.xml, src/main/resources/static/js/post_list_mypage.js, src/main/resources/templates/mypage.html, src/main/resources/templates/posts/post_benefits.html, src/main/resources/templates/posts/post_detail.html, src/main/resources/templates/posts/post_header.html, src/main/resources/templates/posts/post_info_etc.html, src/main/resources/templates/posts/post_list_card.html, src/main/resources/templates/posts/post_modal.html, src/main/resources/templates/posts/post_summary.html, src/main/resources/templates/posts/post_write.html
복지항목은 테스트 용으로 아무거나 넣었습니다.
이제 현지님이 지도만 잘 연동하시면 됩니다.
closes-gh-42
=> 공고 상세 정보 불러오기

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/UserController.java, src/main/java/com/juniorok/juniorok/repository/UserRepository.java, src/main/resources/mapper/user-mapper.xml, src/main/resources/templates/admin_header.html, src/main/resources/templates/admin_users.html, src/main/resources/templates/admin_users_table.html, src/main/resources/templates/admin_users_table_script.html
관리자 - 회원관리입니다.
검색(이메일)
삭제
글쓰기 권한부여/권한삭제
=> feat : 관리자 추가 (회원관리) 

src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/java/com/juniorok/juniorok/dto/Skill.java, src/main/java/com/juniorok/juniorok/form/PostForm.java, src/main/java/com/juniorok/juniorok/repository/PostRepository.java, src/main/java/com/juniorok/juniorok/service/CompanyService.java, src/main/java/com/juniorok/juniorok/service/PostService.java, src/main/resources/mapper/post-mapper.xml, src/main/resources/static/js/post_write.js, src/main/resources/templates/posts/post_list_card.html, src/main/resources/templates/posts/post_write.html
로고 업로드는 폼만 추가했습니다.
기술은 선택 및 저장되도록 했습니다.
그리고 페이징에 문제가 있어 SQL 수정했습니다.
=> 기술 선택 및 저장 그리고 기타 리팩터링

src/main/java/com/juniorok/juniorok/service/UserService.java
=> feat : 회원관리 - 서비스추가

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/AdminController.java, src/main/resources/templates/admin_header.html, src/main/resources/templates/admin_main.html, src/main/resources/templates/header.html
1. 어드민,작성자 true 아이디로 로그인하면 버튼보입니다.
2. 어드민 페이지 메인화면(제대로데이터x) 연결.
**추후 상세 수정예정.
-------
-admin에서 juniorok누르면 juniorok 메인페이지로
-신고관리는 활성화x
=> feat : 관리자 메인페이지

src/main/java/com/juniorok/juniorok/controller/BoardController.java, src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/resources/templates/detailmap.html, src/main/resources/templates/mypage.html, src/main/resources/templates/posts/post_detail.html
1.근무지로 검색되게 되어있습니다.
2.지도에 마커 누르면 다음지도로 이동합니다.
3.이동한 지도에 주소로 검색이 된 결과라 회사이름이 뜨지 않습니다.
**추후 마커에 회사이름 뜨도록 수정 예정.
=> feat : 공고상세페이지 지도api추가

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/BoardController.java, src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/java/com/juniorok/juniorok/repository/PostRepository.java, src/main/java/com/juniorok/juniorok/service/PostService.java, src/main/resources/mapper/post-mapper.xml, src/main/resources/static/js/post_list_mypage.js, src/main/resources/templates/mypage.html
마이페이지에서 검색 및 정렬이 가능하도록 수정하였습니다.
포지션명, 자격요건, 우대요건에 포함된 키워드를 기준으로 정렬합니다.
=> 검색 및 정렬 기능

src/main/java/com/juniorok/juniorok/controller/BoardController.java, src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/resources/mapper/post-mapper.xml, src/main/resources/static/js/detailmap.js, src/main/resources/static/js/post_list_mypage.js, src/main/resources/templates/detailmap.html, src/main/resources/templates/posts/post_detail.html, src/main/resources/templates/posts/post_header.html
마이페이지에서 무한 스크롤이 가능하도록 기능을 추가하였습니다. 헛점이 있기는 하지만... 시간이 없는 관계로 일단은 되게 했습니다. 미리 게시글을 당겨오므로, 무한 스크롤을 확인하려면 스크롤바가 점점 짧아지는 것을 봐야합니다.
지도는 보여드렸던대로... 변경한거 현지님 참고하시라고 기존 코드는 대체로 남겨놨어요.
=> 무한스크롤 페이징 및 지도 출력

src/main/java/com/juniorok/juniorok/controller/BoardController.java
유빈님이 만든 메인화면에 게시물을 불러오도록 컨트롤러를 수정하였습니다.
=> feat: 메인화면 공고 불러오기

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/BoardController.java, src/main/resources/static/css/temp_carousel.css, src/main/resources/static/js/detailmap.js, src/main/resources/static/js/post_list_mypage.js, src/main/resources/static/js/temp_carousel.js, src/main/resources/templates/detailmap.html, src/main/resources/templates/header.html, src/main/resources/templates/posts/post_list_card.html, src/main/resources/templates/posts/post_recommended.html, src/main/resources/templates/temporal_main.html
발표용으로 임시 공고 목록을 추가했습니다.
추가적으로 지도가 여러번 로딩되는 문제도 수정하였습니다.
=> 발표용 임시 목록 추가

src/main/java/com/juniorok/juniorok/config/SecurityConfig.java, src/main/java/com/juniorok/juniorok/controller/PostController.java, src/main/java/com/juniorok/juniorok/repository/PostRepository.java, src/main/java/com/juniorok/juniorok/service/PostService.java, src/main/resources/mapper/post-mapper.xml, src/main/resources/templates/admin_post.html, src/main/resources/templates/admin_post_table.html, src/main/resources/templates/admin_post_table_script.html
=> feat : 관리자 추천공고 등록 & 해제

src/main/resources/templates/posts/post_recommended.html
현지님이 작성하신 추천 공고 설정 기능을 화면에 표시하기 위해 수정하였습니다.
=> feat: 추천 공고 상단 표시

src/main/resources/mapper/post-mapper.xml
=> 추천공고 불러오는 mapper수정

src/main/java/com/juniorok/juniorok/controller/AdminController.java, src/main/java/com/juniorok/juniorok/service/PostService.java
1.관리자 추천공고관련 누락 파일 추가.
2.주석 수정
=> fix : 관리자 추천공고관련 누락 파일 추가.

src/main/resources/templates/admin_post_table_script.html, src/main/resources/templates/posts/post_modify.html
1.관리자 추천공고관련 alert메세지 수정
2.불필요한 ready 삭제
3.글수정페이지-전체 내용 확인용 주석처리
=> fix : 관리자 추천공고관련[ 수정 ]
